apiVersion: chaos-mesh.org/v1alpha1
kind: RemoteCluster
metadata:
 name: remote-cls
spec:
 namespace: "chaos-mesh"
 version: "2.6.2"
 configOverride:
   dashboard:
      create: false
   controllerManager:
      replicaCount: 1
 kubeConfig:
   secretRef:
      name: dev-cls-remote
      namespace: default
      key: dev-cls-remote
