apiVersion: chaos-mesh.org/v1alpha1
kind: RemoteCluster
metadata:
 name: remote-cls
spec:
 namespace: "chaos-mesh"
 version: "2.5.0"
 configOverride:
   dashboard:
      create: false
   controllerManager:
      replicaCount: 1
 kubeConfig:
   secretRef:
      name: remote-cls
      namespace: default
      key: remote-cls
